export type PlayerSeoData = {
  slug: string;
  nick: string;
  name: string;
  teamName: string;
  teamLogo: string;
  nationality: string;
  born: string;
  status: string;
  image: string;
  instagram?: string;
  seoAliases?: string[];
};

export const players: PlayerSeoData[] = [
  {
    slug: 'shurta',
    nick: 'Shurta',
    name: 'Saliq Tariq',
    teamName: 'Destroyer Esports',
    teamLogo: '/Des-Logo.jpg',
    nationality: 'Pakistan',
    born: 'August 17, 2005 (age 20)',
    status: 'Not-Active',
    image: '/ShurtaG-Esport Pic.jpg',
    instagram: 'https://www.instagram.com/ig_shurta',
    seoAliases: ['Shurta G PUBG', 'Shurta PUBGM', 'ig_shurta'],
  },
  {
    slug: 'falak',
    nick: 'Falak',
    name: 'Falak Sher',
    teamName: '4Thrives',
    teamLogo: '/4thirveslogo.png',
    nationality: 'Pakistan',
    born: 'April 25, 2007(age 19)',
    status: 'Active',
    image: '/4tfalak-picfix.jpg',
    instagram: 'https://www.instagram.com/falakpubgm',
    seoAliases: ['Falak PUBG', 'Falak PUBGM', 'falakpubgm'],
  },
  {
    slug: 'maade',
    nick: 'Maade',
    name: 'Muhammad MaadeKarab',
    teamName: 'Rising Phantom Gunners',
    teamLogo: '/rpglogo.jpg',
    nationality: 'Pakistan',
    born: 'Nov 4, 2008 (age 17)',
    status: 'Active',
    image: '/Maadepicfixed.png',
    instagram: 'https://www.instagram.com/ig_maade',
    seoAliases: ['Maade PUBG', 'Maade PUBGM', 'ig_maade'],
  },
  {
    slug: 'aspekt',
    nick: 'Aspekt',
    name: 'Ahmed',
    teamName: 'F2D Esports',
    teamLogo: '/F2D-EsportLogo.jpg',
    nationality: 'Pakistan',
    born: 'May 24, 2004 (age 22)',
    status: 'Active',
    image: '/Aspekt-Esportpicreplace.jpg',
    instagram: 'https://www.instagram.com/aspekt_pubgm',
    seoAliases: ['Aspekt PUBG', 'Aspekt PUBGM', 'aspekt_pubgm'],
  },
  {
    slug: 'alphaboy',
    nick: 'AlphaBoy',
    name: 'Muhammad Huzaifa Ali',
    teamName: 'Seventh Element',
    teamLogo: '/SeventhElement-Logo.png',
    nationality: 'Pakistan',
    born: 'January 1, 2006 (age 20)',
    status: 'Active',
    image: '/Alphaboy-EsportPic.jpg',
    instagram: 'https://www.instagram.com/alphaboyy.1',
    seoAliases: ['AlphaBoy PUBG', 'AlphaBoy PUBGM', 'alphaboyy.1'],
  },
  {
    slug: 'chief-og',
    nick: 'Chief OG',
    name: 'Muhammad Izhar',
    teamName: 'Galacticous',
    teamLogo: '/Galacticous-logo.jpeg',
    nationality: 'Pakistan',
    born: 'June 4, 2005 (age 20)',
    status: 'Active',
    image: '/Chief-Esport Pic.jpg',
    instagram: 'https://www.instagram.com/cheifog_pubg',
    seoAliases: ['Chief OG PUBG', 'Chief OG PUBGM', 'cheifog_pubg'],
  },
  {
    slug: 'eminent',
    nick: 'Eminent',
    name: 'Khuzaima',
    teamName: 'FMA Esports',
    teamLogo: '/fma-esports-logo.jpg',
    nationality: 'Pakistan',
    born: 'TBD',
    status: 'Active',
    image: '/FmaxEminent-Pic.png',
    instagram: 'https://www.instagram.com/lazy_.khuzaima',
    seoAliases: ['Eminent PUBG', 'Eminent PUBGM', 'lazy_.khuzaima'],
  },
  {
    slug: 'beastopie',
    nick: 'Beastopie',
    name: 'Muhammad Imad Habib',
    teamName: 'Freestyle',
    teamLogo: '/freestyle-logo.jpg',
    nationality: 'Pakistan',
    born: 'February 5, 2007 (age 19)',
    status: 'Active',
    image: '/Beast-EsportPic.jpeg',
    instagram: 'https://www.instagram.com/beastopie',
    seoAliases: ['Beastopie PUBG', 'Beastopie PUBGM'],
  },
  {
    slug: 'chaos',
    nick: 'Chaos',
    name: 'Ali',
    teamName: 'H2E Esports',
    teamLogo: '/h2elogo.png',
    nationality: 'Pakistan',
    born: '24 March 2005 (age 20)',
    status: 'Free Agent',
    image: '/chaospicturenew.jpg',
    instagram: 'https://www.instagram.com/chaos.xi',
    seoAliases: ['Chaos PUBG', 'Chaos PUBGM', 'chaos.xi'],
  },
  {
    slug: 'falcon',
    nick: 'Falcon',
    name: 'Fardeen Rogatia',
    teamName: 'Oxy Esports',
    teamLogo: '/Oxylogo.png',
    nationality: 'Pakistan',
    born: '19 Dec 2004 (age 21)',
    status: 'Active',
    image: '/FalconFixedEsppic.jpeg',
    instagram: 'https://www.instagram.com/ig_falcongaming',
    seoAliases: ['Falcon PUBG', 'Falcon PUBGM', 'Falcon PUBG Mobile', 'ig_falcongaming'],
  },
  {
    slug: 'smokie',
    nick: 'Smokie',
    name: 'Muhammad Ali',
    teamName: 'Son of Anarchy',
    teamLogo: '/SonofAnarchylogo.jpeg',
    nationality: 'Pakistan',
    born: '10 Nov 2008 (age 17)',
    status: 'Active',
    image: '/SmokieEspPic.jpeg',
    instagram: 'https://www.instagram.com/smokiefps',
    seoAliases: ['Smokie PUBG', 'Smokie PUBGM', 'smokiefps'],
  },
  {
    slug: 'jagga',
    nick: 'Jagga',
    name: 'Muhammad Saqib Khan Niazi',
    teamName: 'Hyper Esports',
    teamLogo: '/Hyperlogo.jpg',
    nationality: 'Pakistan',
    born: 'May 4, 2002 (age 24)',
    status: 'Active',
    image: '/jaggaesppic.jpg',
    instagram: 'https://www.instagram.com/pubg.jagga',
    seoAliases: ['Jagga PUBG', 'Jagga PUBGM', 'pubg.jagga'],
  },
  {
    slug: 'hadee',
    nick: 'Hadi',
    name: 'Abdul Hadi',
    teamName: 'Mythicals',
    teamLogo: '/mythicalslogo.jpg',
    nationality: 'Pakistan',
    born: 'Sep 6, 2006 (age 19)',
    status: 'Not Active',
    image: '/mythhadiesppic.jpg',
     instagram: 'https://www.instagram.com/_hadihehe',
    seoAliases: ['Hadi PUBG', 'Hadee PUBG', 'Hadi PUBGM'],
  },
  {
    slug: 'bunny',
    nick: 'Bunny',
    name: 'Arbaz',
    teamName: 'Demolition 5',
    teamLogo: '/d5logo.png',
    nationality: 'Pakistan',
    born: '26 October 2007 (age 19)',
    status: 'Active',
    image: '/d5bunnypic.jpg',
    instagram: 'https://www.instagram.com/ig.bunnypubgm',
    seoAliases: ['Bunny PUBG', 'Bunny PUBGM', 'ig.bunnypubgm'],
  },
  {
    slug: 'arsim',
    nick: 'Arsim',
    name: 'Arsim',
    teamName: '404 Esports',
    teamLogo: '/404logo.png',
    nationality: 'Pakistan',
    born: '',
    status: 'Active',
    image: '/arsimnew.jpg',
    instagram: 'https://www.instagram.com/ig.arsimop',
    seoAliases: ['Arsim PUBG', 'Arsimop PUBG', 'Arsim PUBGM', 'ig.arsimop'],
  },
   {
    slug: 'gyro',
    nick: 'Gyro',
    name: 'Inam-ur-Rehman',
    teamName: 'Unix Esports',
    teamLogo: '/Unixlogo.jpg',
    nationality: 'Pakistan',
    born: '01 January 2006 (age 20)',
    status: 'Active',
    image:'/gyroEsp-pic.png',
    instagram: 'https://www.instagram.com/ig.gyronub',
    seoAliases: ['Gyro PUBG', 'Unixgyro PUBG', 'Gyro PUBGM', 'Inam gyro'],
  },
  {
    slug: 'hackur',
    nick: 'Hackur',
    name: 'Umair Mengal',
    teamName: 'FMA Esports',
    teamLogo: '/fma-esports-logo.jpg',
    nationality: 'Pakistan',
    born: '01 January 2006 (age 20)',
    status: 'Active',
    image:'/HackurEspPic.png',
    instagram: 'https://www.instagram.com/ig_hackur1',
    seoAliases: ['Umair PUBG', 'fmaHackur PUBG', 'fma PUBGM', 'hackur pubg'],
  },
   {
    slug: 'codex',
    nick: 'Codex',
    name: 'Muhammad Ghous',
    teamName: 'A8 Academy',
    teamLogo: '/A8Logo.jpg',
    nationality: 'Pakistan',
    born: '20 January 2005 (age 21)',
    status: 'Active',
    image:'/Codex-EspPic.png',
    instagram: 'https://www.instagram.com/codex.sys',
    seoAliases: ['Codex PUBG', 'Ghous PUBG', 'Codex Ghous PUBGM', 'Coach Pakistan pubg'],
  },
   {
    slug: 'gunda',
    nick: 'Gunda',
    name: 'Uzair Khalid',
    teamName: 'Global Wiz Esports',
    teamLogo: '/globalwizesportslogo.jpg',
    nationality: 'Pakistan',
    born: '',
    status: 'Active',
    image:'/GundaEspPic.jpeg',
    instagram: 'https://www.instagram.com/iggunda111',
    seoAliases: ['Uzair Khalid PUBG', 'Gunda PUBGM', 'iggunda111'],
  },
   {
    slug: 'sami',
    nick: 'Sami',
    name: 'Muhammad Sami',
    teamName: 'The Executor',
    teamLogo: '/executorlogo.jpg',
    nationality: 'Pakistan',
    born: '11 November 2003 (age 23)',
    status: 'Active',
    image:'/MuhammadSamiEspPic.jpg',
    instagram: 'https://www.instagram.com/samijaved07_',
    seoAliases: ['Sami pubg', 'Muhammad Sami PUBGM', 'samijaved07_'],
  },
   {
    slug: 'jin',
    nick: 'Jin',
    name: 'Toseef Haider',
    teamName: '3x Esports',
    teamLogo: '/3xlogo.png',
    nationality: 'Pakistan',
    born: '24 December 2002 (age 24)',
    status: 'Active',
    image:'/jinEsportPic.jpg',
    instagram: 'https://www.instagram.com/ig_jin.op',
    seoAliases: ['Jin pubg', 'Touseef Haider PUBGM', 'ig_jin.op'],
  },
  {
    slug: 'captain',
    nick: 'Captain',
    name: 'Shahzada Anzal',
    teamName: 'Red Saints',
    teamLogo: '/RST Esports.png',
    nationality: 'Pakistan',
    born: '24 December 2002 (age 24)',
    status: 'Active',
    image:'/captnEspPic.jpg',
    instagram: 'https://www.instagram.com/ig.captn01',
    seoAliases: ['RST Captain pubg', 'Captn PUBGM', 'Shahzada Anzal'],
  },
  {
    slug: 'baba',
    nick: 'Baba',
    name: 'Asad Nadeem Mughal',
    teamName: 'WallStreet Bets',
    teamLogo: '/WallStreet Bets Logo.jpg',
    nationality: 'Pakistan',
    born: '',
    status: 'Not Active',
    image: '',
    seoAliases: ['Baba PUBG', 'Baba PUBGM', 'Asad Nadeem Mughal'],
  },
  {
    slug: '420boy',
    nick: 'Khan420',
    name: 'Abdullah Khan',
    teamName: 'Viper Xotics',
    teamLogo: '',
    nationality: 'Pakistan',
    born: '',
    status: 'Retired',
    image: '',
    seoAliases: ['Khan420 PUBG', 'Khan420 PUBGM', 'Abdullah Khan'],
  },
];

export const playersBySlug = Object.fromEntries(
  players.map((player) => [player.slug, player])
) as Record<string, PlayerSeoData>;

export function getPlayer(slug: string) {
  return playersBySlug[slug.toLowerCase()];
}

export function getPlayerDescription(player: PlayerSeoData) {
  const aliases = player.seoAliases?.slice(0, 2).join(', ');
  const aliasText = aliases ? ` Also known as ${aliases}.` : '';

  return `${player.nick.toUpperCase()} PUBG Mobile Player. (${player.teamName}) > ${player.nick} esports statistics overview, tournaments, achievements, team history, status, and profile.${aliasText}`;
}

export function getPlayerSeoTitle(player: PlayerSeoData) {
  return `${player.nick.toUpperCase()} - PUBG Mobile Player Profile`;
}

export function getSiteUrl() {
  return (process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000').replace(/\/$/, '');
}

export function getAbsoluteUrl(path: string) {
  return `${getSiteUrl()}${path.startsWith('/') ? path : `/${path}`}`;
}
